version: '3.4'

services:
  dbmigrator:
    image: registry.antosubash.com/migrator:dev
    environment:
      ConnectionStrings__SaaSService: "User ID=postgres;Password=postgres_password;Host=206.189.147.1;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=postgres_password;Host=206.189.147.1;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=postgres_password;Host=206.189.147.1;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=postgres_password;Host=206.189.147.1;Port=5432;Database=TaskyProjectService;Pooling=false;"